/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoexp;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.clipsrules.jni.Environment;

/**
 *
 * @author diego's
 */
public class AspectoPensamiento extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    
    DefaultTableModel m;
    GridBagConstraints gbc;
    GridBagLayout gridbag ;
    
    private ArrayList lista;
    private ArrayList l1;
    private ArrayList l2;
    private ArrayList l3;
    private ArrayList l4;
    private ArrayList l5;
    
    
    private Environment clips;
    
    public AspectoPensamiento() {
        initComponents();
        jButton2.setVisible(false);
        lista=new ArrayList();
        l1=new ArrayList();
        l2=new ArrayList();
        l3=new ArrayList();
        l4=new ArrayList();
        l5=new ArrayList();
        this.setSize(990, 500);
        this.setLocationRelativeTo(null);
        m = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column!=0;
            }
        };
        
        m.addColumn("LÁMINA");
        m.addColumn("");
        m.addColumn("RESPUESTA");
        
        m.addRow(new Object[]{"1","Busca la niña que lleva un cubo y una pala",""});
        m.addRow(new Object[]{"2","En el zoológico vimos algunos animales salvajes en sus jaulas ",""});
        m.addRow(new Object[]{"3","Los niños colgaron una cesta de flores en la puerta,luego tocaron el timbrey escaparon",""});
        m.addRow(new Object[]{"4","En el otroño papá junta las hojas y las quema",""});
        m.addRow(new Object[]{"5","En navidad los niños prepararon una tarta y la colocaron en una fuente en la ventana",""});
        m.addRow(new Object[]{"6","María preparó su cajijta con comida,dos libros y una caja de lápices para llevar a la escuela",""});
        m.addRow(new Object[]{"7","Papá llevó a Juan y a su amigo Joge al circo, alli vieron a un payaso motado alrevés en un caballo, con  una monura muy adornada",""});
        m.addRow(new Object[]{"8","En Suiza, las vacas usan campanillas colgadas de sus cuellos, de modo el el niño pueda encontrarlas cuando se alejan",""});
        m.addRow(new Object[]{"9","Ricardo construyó una asa de dos pisos y e puso una chimenea ",""});
        m.addRow(new Object[]{"10","El farmacéutico vende medicinas para la gente enferma",""});
        m.addRow(new Object[]{"11","El hombre estaba leyendo un aviso que colgaba de la valla",""});
        m.addRow(new Object[]{"12","<<El hombre cojo no podía caminar hasta que consigui unas...>> ",""});
        m.addRow(new Object[]{"13","<<El niño del grangero fue al pozo para sacar un...>>",""});
        m.addRow(new Object[]{"14","<<Después de cortar la hierba la guardan en un..>> ",""});
        
        for(int i=0;i<28;i++){
            m.isCellEditable(i,1);
            m.isCellEditable(i,2);
        }
        jTable1.setRowHeight(18);
        jTable1.setModel(m);
        
        TableColumn col0 =jTable1.getColumnModel().getColumn(0);
        TableColumn col =jTable1.getColumnModel().getColumn(1);
        TableColumn col1 =jTable1.getColumnModel().getColumn(2);
        
        col0.setPreferredWidth(10);
        col.setPreferredWidth(720);
        col1.setPreferredWidth(40);
        
        clips=new Environment();
        //clips.eval("(watch all)");
        clips.load("inicio.clp");
        clips.load("inicio2.clp");
        
    }
    
    
    public void datos(String cedula, String nombres, String apellidos, String fechaNac){
        jtcedula.setText(cedula);
        jtnombres.setText(nombres);
        jtapellidos.setText(apellidos);
        jtfechaNac.setText(fechaNac);
    }
    
    public void listas(ArrayList li1,ArrayList li2,ArrayList li3,ArrayList li4,ArrayList li5){
        l1=li1;
        l2=li2;
        l3=li3;
        l4=li4;
        l5=li5;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel30 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jtcedula = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jtnombres = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jtapellidos = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jtfechaNac = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel30.setText("jLabel30");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exploracion Fonológica y Fonética");

        jPanel1.setPreferredSize(new java.awt.Dimension(390, 105));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setPreferredSize(new java.awt.Dimension(139, 219));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DATOS PERSONALES ");
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 45));
        jPanel11.add(jLabel1);

        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.setPreferredSize(new java.awt.Dimension(10, 450));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel31.setText("     Cedula:     ");
        jLabel31.setPreferredSize(new java.awt.Dimension(85, 14));
        jPanel7.add(jLabel31);

        jtcedula.setEditable(false);
        jtcedula.setPreferredSize(new java.awt.Dimension(29, 20));
        jPanel7.add(jtcedula);

        jPanel11.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(10, 450));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));

        jLabel34.setText("     Nombres:      ");
        jLabel34.setPreferredSize(new java.awt.Dimension(95, 14));
        jPanel8.add(jLabel34);

        jtnombres.setEditable(false);
        jPanel8.add(jtnombres);

        jPanel11.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(10, 450));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

        jLabel35.setText("     Apellidos:    ");
        jLabel35.setPreferredSize(new java.awt.Dimension(85, 14));
        jPanel9.add(jLabel35);

        jtapellidos.setEditable(false);
        jPanel9.add(jtapellidos);

        jPanel11.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(10, 450));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));

        jLabel37.setText("     Fecha de nacimiento:   ");
        jLabel37.setPreferredSize(new java.awt.Dimension(155, 14));
        jPanel10.add(jLabel37);

        jtfechaNac.setEditable(false);
        jPanel10.add(jtfechaNac);

        jPanel11.add(jPanel10);

        jPanel1.add(jPanel11, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(394, 30));
        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jButton1.setText("SIGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        jButton2.setText("NUEVO REGISTRO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(30, 300));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(50, 403));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(160, 402));

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "CORRECTO", "Title 3", "INCORRECTO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel12.setPreferredSize(new java.awt.Dimension(372, 25));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aspecto Pensamiento");
        jPanel12.add(jLabel2);

        jPanel3.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Recomendacion r=new Recomendacion();
        String ced=jtcedula.getText();
        String nom=jtnombres.getText();
        String ape=jtapellidos.getText();
        String f=jtfechaNac.getText();
        Double c=0.0;
        Double ic=0.0;
        String niño="(assert (niño (cedula "+ced+")(nombres \""+nom+"\")(apellidos \""+ape+"\")(fechaNac \""+f+"\")))";
        clips.eval(niño);
        String t="(assert (pensamiento (cedula "+ ced+")(pregunta \"";
        String respuesta ="";
        for (int j = 0; j < jTable1.getRowCount(); j++) {
            respuesta = (String) jTable1.getValueAt(j, 2).toString().toUpperCase();
            if (respuesta.equals("+") || respuesta.equals("-")) {
                if (respuesta.equals("+")) {
                    lista.add(t + jTable1.getValueAt(j, 1) + "\")(respuesta " + respuesta + ")))");
                    if (respuesta.equals("+")) {
                        c++;
                    }
                } else {
                    if (respuesta.equals("-")) {
                        lista.add(t + jTable1.getValueAt(j, 1) + "\")(respuesta " + respuesta + ")))");
                        if (respuesta.equals("-")) {
                            ic++;
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Los signos ingresados no son incorrectos. Se debe calificar con un + o un -");
                jTable1.setValueAt("", j, 2);
            }
        }
        if(lista.size()==14){
            for(int i=0;i<lista.size();i++){
                //System.out.println(lista.get(i));
                //clips.eval(lista.get(i).toString());
            }
            String res="(assert (respPensamiento (cedula "+ced+")(correctas "+(Math.round(((c*10)/14) *100))/100+")(incorrectas "+(Math.round(((ic*10)/14) *100))/100+")))";
            lista.add(res);
            JOptionPane.showMessageDialog(null, "El resultado del test realizado al niño "+
                    nom+" "+ape+" es de: Correctas="+((c*10)/14)+"/10 Incorrectas="+((ic*10)/14)+"/10");
            
            String rrr =clips.eval("(facts 75)").toString();
            this.guardar();
           System.out.println(clips.eval("(facts)"));
            //clips.eval(res);
            
            //System.out.println(clips.eval("?recomend").toString());
            r.setVisible(true);
            //System.out.println(">>>>>>>>>>>>>>>>>>>        recomendacion        "+clips.eval("?recomend")); 
            //System.out.println("RECOMENDACION:::::::::::::"+clips.eval("(facts 75)"));
            r.recomend(rrr);
            jButton1.setEnabled(false);
            jButton2.setVisible(true);
            //this.hide();
            
        }
        //System.out.println("Correctas: "+c+"     Incorrectas: "+ic);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        super.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void guardar(){
        //System.out.println("Lista 1:");
        for(int i=0;i<l1.size();i++){
            clips.eval(l1.get(i)+"");
            //System.out.println(l1.get(i));
        }
        //System.out.println("Lista 2:");
        for(int i=0;i<l2.size();i++){
            clips.eval(l2.get(i)+"");
            //System.out.println(l2.get(i));
        }
        //System.out.println("Lista 3:");
        for(int i=0;i<l3.size();i++){
            clips.eval(l3.get(i)+"");
            //System.out.println(l3.get(i));
        }
        //System.out.println("Lista 4:");
        for(int i=0;i<l4.size();i++){
            clips.eval(l4.get(i)+"");
            //System.out.println(l4.get(i));
        }
        //System.out.println("Lista 5:");
        for(int i=0;i<l5.size();i++){
            clips.eval(l5.get(i)+"");
            //System.out.println(l5.get(i));
        }
        //System.out.println("Lista 6:");
        for(int i=0;i<lista.size();i++){
            clips.eval(lista.get(i)+"");
            //System.out.println(lista.get(i));
        }
        //System.out.println(clips.eval("(facts)"));
        clips.eval("(run)");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AspectoPensamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AspectoPensamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AspectoPensamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AspectoPensamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AspectoPensamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtapellidos;
    private javax.swing.JTextField jtcedula;
    private javax.swing.JTextField jtfechaNac;
    private javax.swing.JTextField jtnombres;
    // End of variables declaration//GEN-END:variables
}
