/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoexp;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.clipsrules.jni.Environment;

/**
 *
 * @author diego's
 */
public class ExploracionFonolFonet extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    
    DefaultTableModel m;
    GridBagConstraints gbc;
    GridBagLayout gridbag ;
    private ArrayList l;
    
    private Environment clips;
    
    public ExploracionFonolFonet() {
        initComponents();
        this.setSize(550, 730);
        this.setLocationRelativeTo(null);
        m = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column!=0;
            }
        };
        l=new ArrayList();
        m.addColumn("N°");
        m.addColumn("");
        m.addColumn("RESPUESTA");
        
        m.addRow(new Object[]{"1","Pronunciacion del vocablo /p/",""});
        m.addRow(new Object[]{"2","Pronunciacion del vocablo /b/",""});
        m.addRow(new Object[]{"3","Pronunciacion del vocablo /m/",""});
        m.addRow(new Object[]{"4","Pronunciacion del vocablo /d/",""});
        m.addRow(new Object[]{"5","Pronunciacion del vocablo /t/",""});
        m.addRow(new Object[]{"6","Pronunciacion del vocablo /f/",""});
        m.addRow(new Object[]{"7","Pronunciacion del vocablo /rr/",""});
        m.addRow(new Object[]{"8","Pronunciacion del vocablo /r/",""});
        m.addRow(new Object[]{"9","Pronunciacion del vocablo /l/",""});
        m.addRow(new Object[]{"10","Pronunciacion del vocablo /n/",""});
        m.addRow(new Object[]{"11","Pronunciacion del vocablo /s/",""});
        m.addRow(new Object[]{"12","Pronunciacion del vocablo /ch/",""});
        m.addRow(new Object[]{"13","Pronunciacion del vocablo /ll/",""});
        m.addRow(new Object[]{"14","Pronunciacion del vocablo /ñ/",""});
        m.addRow(new Object[]{"15","Pronunciacion del vocablo /k/",""});
        m.addRow(new Object[]{"16","Pronunciacion del vocablo /g/",""});
        m.addRow(new Object[]{"17","Pronunciacion del vocablo /pl/",""});
        m.addRow(new Object[]{"18","Pronunciacion del vocablo /bl/",""});
        m.addRow(new Object[]{"19","Pronunciacion del vocablo /fl/",""});
        m.addRow(new Object[]{"20","Pronunciacion del vocablo /cl/",""});
        m.addRow(new Object[]{"21","Pronunciacion del vocablo /gl/",""});
        m.addRow(new Object[]{"22","Pronunciacion del vocablo /pr/",""});
        m.addRow(new Object[]{"23","Pronunciacion del vocablo /br/",""});
        m.addRow(new Object[]{"24","Pronunciacion del vocablo /dr/",""});
        m.addRow(new Object[]{"25","Pronunciacion del vocablo /tr/",""});
        m.addRow(new Object[]{"26","Pronunciacion del vocablo /fr/",""});
        m.addRow(new Object[]{"27","Pronunciacion del vocablo /kr/",""});
        m.addRow(new Object[]{"28","Pronunciacion del vocablo /gr/",""});
        
        for(int i=0;i<28;i++){
            m.isCellEditable(i,1);
            m.isCellEditable(i,2);
        }
        jTable1.setRowHeight(18);
        jTable1.setModel(m);
        
        TableColumn col0 =jTable1.getColumnModel().getColumn(0);
        TableColumn col =jTable1.getColumnModel().getColumn(1);
        TableColumn col1 =jTable1.getColumnModel().getColumn(2);
        
        col0.setPreferredWidth(20);
        col.setPreferredWidth(200);
        col1.setPreferredWidth(50);
        
        clips=new Environment();
        
    }
    
    
    public void datos(String cedula, String nombres, String apellidos, String fechaNac){
        jtcedula.setText(cedula);
        jtnombres.setText(nombres);
        jtapellidos.setText(apellidos);
        jtfechaNac.setText(fechaNac);
    }
    
    public void lista(ArrayList list){
        l=list;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel30 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jtcedula = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jtnombres = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jtapellidos = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jtfechaNac = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel30.setText("jLabel30");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exploracion Fonológica y Fonética");
        setPreferredSize(new java.awt.Dimension(490, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(390, 105));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setPreferredSize(new java.awt.Dimension(139, 219));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DATOS PERSONALES ");
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 45));
        jPanel11.add(jLabel1);

        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.setPreferredSize(new java.awt.Dimension(10, 450));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel31.setText("     Cedula:     ");
        jLabel31.setPreferredSize(new java.awt.Dimension(85, 14));
        jPanel7.add(jLabel31);

        jtcedula.setEditable(false);
        jtcedula.setPreferredSize(new java.awt.Dimension(29, 20));
        jPanel7.add(jtcedula);

        jPanel11.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(10, 450));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));

        jLabel34.setText("     Nombres:      ");
        jLabel34.setPreferredSize(new java.awt.Dimension(95, 14));
        jPanel8.add(jLabel34);

        jtnombres.setEditable(false);
        jPanel8.add(jtnombres);

        jPanel11.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(10, 450));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

        jLabel35.setText("     Apellidos:    ");
        jLabel35.setPreferredSize(new java.awt.Dimension(85, 14));
        jPanel9.add(jLabel35);

        jtapellidos.setEditable(false);
        jPanel9.add(jtapellidos);

        jPanel11.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(10, 450));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));

        jLabel37.setText("     Fecha de nacimiento:   ");
        jLabel37.setPreferredSize(new java.awt.Dimension(155, 14));
        jPanel10.add(jLabel37);

        jtfechaNac.setEditable(false);
        jPanel10.add(jtfechaNac);

        jPanel11.add(jPanel10);

        jPanel1.add(jPanel11, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(394, 30));
        jPanel6.setLayout(new java.awt.CardLayout());

        jButton1.setText("SIGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, "card2");

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(30, 300));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(50, 403));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(160, 402));

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "CORRECTO", "INCORRECTO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel12.setPreferredSize(new java.awt.Dimension(372, 25));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Exploracion Fonológica y Fonética");
        jPanel12.add(jLabel2);

        jPanel3.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OrdenCopleja oc=new OrdenCopleja();
        ArrayList lista=new ArrayList();
        String ced=jtcedula.getText();
        String nom=jtnombres.getText();
        String ape=jtapellidos.getText();
        String f=jtfechaNac.getText();
        oc.datos(ced, nom, ape, f);
        double c=0;
        double ic=0;
        //String niño="(assert (niño (cedula "+ced+")(nombres \""+nom+"\")(apellidos \""+ape+"\")(fechaNac \""+f+"\")))";
        //clips.eval(niño);
        String t="(assert (fonolFonet (cedula "+ ced+")(pregunta \"";
        String respuesta ="";
        for (int j = 0; j < jTable1.getRowCount(); j++) {
            respuesta = (String) jTable1.getValueAt(j, 2).toString().toUpperCase();
            if (respuesta.equals("+") || respuesta.equals("-")) {
                if (respuesta.equals("+")) {
                    lista.add(t + jTable1.getValueAt(j, 1) + "\")(respuesta " + respuesta + ")))");
                    if (respuesta.equals("+")) {
                        c++;
                    }
                } else {
                    if (respuesta.equals("-")) {
                        lista.add(t + jTable1.getValueAt(j, 1) + "\")(respuesta " + respuesta + ")))");
                        if (respuesta.equals("-")) {
                            ic++;
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Los signos ingresados no son incorrectos. Se debe calificar con un + o un -");
                jTable1.setValueAt("", j, 2);
            }
        }
        if(lista.size()==28){
            for(int i=0;i<lista.size();i++){
                //System.out.println(lista.get(i));
                //clips.eval(lista.get(i).toString());
            }
            String res="(assert (respFonol (cedula "+ced+")(correctas "+Math.round(((c*10)/28))+")(incorrectas "+Math.round(((ic*10)/28))+")))"; 
            lista.add(res);
            JOptionPane.showMessageDialog(null, "El resultado del test realizado al niño "+
                    nom+" "+ape+" es de: Correctas="+((c*10)/28)+"/10 Incorrectas="+((ic*10)/28)+"/10");
            //clips.eval(res);
            oc.setVisible(true);
            oc.lista(l, lista);
            //this.hide();
            jButton1.setEnabled(false);
            //System.out.println(clips.eval("(facts)"));
            //System.out.println("Correctas: "+c+"     Incorrectas: "+ic);
        }        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExploracionFonolFonet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExploracionFonolFonet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExploracionFonolFonet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExploracionFonolFonet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExploracionFonolFonet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtapellidos;
    private javax.swing.JTextField jtcedula;
    private javax.swing.JTextField jtfechaNac;
    private javax.swing.JTextField jtnombres;
    // End of variables declaration//GEN-END:variables
}
